startPath: ""
hideHidden: true
ignoreSuffixes:
  - .exe
  - .app
columns:
  showType: true
  showModified: true
  showSize: true
sort:
  field: name
  order: asc
rainbow:
  speed: 2.000000000000001
  direction: normal
  width: 10.5
  brightness: 0.37
tools:
  rename:
    recursive: true
  delete:
    recursive: true
